# SPDX-License-Identifier: GPL-3.0-or-later
# Default demonstration configuration. Start/check from the repository root.
# Replace the demonstration CN rules and upstreams before production use.
listen_udp=127.0.0.1:15362
listen_tcp=127.0.0.1:15362
cn_domain_file=c/examples/cn-site.txt
cn_upstream=127.0.0.1:5301
foreign_upstream=tcp://127.0.0.1:5302
cache_size=1024
cache_lazy_ttl=0
tcp_idle_timeout=30
